package com.asdoi.corona.johnshopkins

import com.asdoi.corona.ParseError
import com.asdoi.corona.model.LiveTicker
import com.asdoi.corona.model.LiveTickerParser
import org.json.JSONArray
import org.json.JSONObject
import org.jsoup.Jsoup
import org.jsoup.nodes.Document
import java.io.IOException
import java.text.SimpleDateFormat
import java.util.*


object JHUParser : LiveTickerParser() {
    private const val DOCUMENT_URL = "https://disease.sh/v3/covid-19/jhucsse"

    private fun parseLiveTickers(document: Document, vararg locations: String): List<LiveTicker> {
        val locationsList: MutableList<String> = mutableListOf()
        for (location in locations) {
            locationsList.add(location.uppercase())
        }

        val tickers: MutableList<LiveTicker> = mutableListOf()

        try {
            val json = JSONArray(document.text())

            for (jsonIndex in 0 until json.length()) {
                val jsonObject: JSONObject = json.getJSONObject(jsonIndex)
                val country = jsonObject.getString("country")
                val province = jsonObject.get("province").toString()
                val location = if (province == "null") country else province
                if (locationsList.contains(location.uppercase())) {
                    try {
                        val stats = jsonObject.getJSONObject("stats")
                        val confirmed = stats.getInt("confirmed")
                        val deaths = stats.getInt("deaths")
                        val recoveredString = stats.get("recovered").toString()
                        val recovered =
                            if (recoveredString == "null") -1 else recoveredString.toInt()
                        val updatedAt = jsonObject.getString("updatedAt")
                        val lastUpdate: Calendar =
                            try {
                                val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)

                                val calendar = Calendar.getInstance()
                                calendar.time = dateFormat.parse(updatedAt)!!
                                calendar
                            } catch (e: Exception) {
                                e.printStackTrace()
                                Calendar.getInstance()
                            }

                        tickers.add(
                            JHUTicker(
                                location,
                                lastUpdate,
                                confirmed,
                                deaths,
                                recovered
                            )
                        )
                    } catch (e: Exception) {
                        e.printStackTrace()
                        tickers.add(
                            ParseError(
                                location,
                                JHUTicker.DATA_SOURCE,
                                JHUTicker.VISIBLE_DATA_SOURCE,
                                e
                            )
                        )
                    }
                }
            }

        } catch (e: Exception) {
            e.printStackTrace()
            tickers.add(
                ParseError(JHUTicker.DATA_SOURCE, JHUTicker.VISIBLE_DATA_SOURCE, e)
            )
        }

        return tickers
    }

    fun parse(document: Document, vararg locations: String): List<LiveTicker> {
        return parseLiveTickers(document, *locations)
    }

    fun parseNoErrors(document: Document, vararg locations: String) =
        parse(document, *locations).filter { !it.isError() }

    fun parseNoInternalErrors(document: Document, vararg locations: String) =
        parse(document, *locations).filter {
            if (it.isError()) {
                !(it as ParseError).isInternalError()
            } else
                true
        }

    @Throws(IOException::class)
    fun downloadDocument(): Document {
        return Jsoup.connect(DOCUMENT_URL)
            .ignoreHttpErrors(true)
            .ignoreContentType(true)
            .get()
    }

    @Throws(IOException::class)
    override fun parse(vararg locations: String): List<LiveTicker> {
        return parse(downloadDocument(), *locations)
    }

    override fun getSuggestions(): List<String> {
        return listOf(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burma",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo (Brazzaville)",
            "Congo (Kinshasa)",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Diamond Princess",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Holy See",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Korea",
            "South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "MS Zaandam",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan*",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "US",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "West Bank and Gaza",
            "Yemen",
            "Zambia",
            "Zimbabwe",
            "Australian Capital Territory",
            "New South Wales",
            "Northern Territory",
            "Queensland",
            "South Australia",
            "Tasmania",
            "Victoria",
            "Western Australia",
            "Antwerp",
            "Brussels",
            "East Flanders",
            "Flemish Brabant",
            "Hainaut",
            "Liege",
            "Limburg",
            "Namur",
            "Unknown",
            "Walloon Brabant",
            "West Flanders",
            "Acre",
            "Alagoas",
            "Amapa",
            "Amazonas",
            "Bahia",
            "Ceara",
            "Distrito Federal",
            "Espirito Santo",
            "Goias",
            "Maranhao",
            "Mato Grosso",
            "Mato Grosso do Sul",
            "Minas Gerais",
            "Para",
            "Paraiba",
            "Parana",
            "Pernambuco",
            "Piaui",
            "Rio Grande do Norte",
            "Rio Grande do Sul",
            "Rio de Janeiro",
            "Rondonia",
            "Roraima",
            "Santa Catarina",
            "Sao Paulo",
            "Sergipe",
            "Tocantins",
            "Alberta",
            "British Columbia",
            "Grand Princess",
            "Manitoba",
            "New Brunswick",
            "Newfoundland and Labrador",
            "Northwest Territories",
            "Nova Scotia",
            "Nunavut",
            "Ontario",
            "Prince Edward Island",
            "Quebec",
            "Repatriated Travellers",
            "Saskatchewan",
            "Yukon",
            "Antofagasta",
            "Araucania",
            "Arica y Parinacota",
            "Atacama",
            "Aysen",
            "Biobio",
            "Coquimbo",
            "Los Lagos",
            "Los Rios",
            "Magallanes",
            "Maule",
            "Metropolitana",
            "Nuble",
            "OHiggins",
            "Tarapaca",
            "Valparaiso",
            "Anhui",
            "Beijing",
            "Chongqing",
            "Fujian",
            "Gansu",
            "Guangdong",
            "Guangxi",
            "Guizhou",
            "Hainan",
            "Hebei",
            "Heilongjiang",
            "Henan",
            "Hong Kong",
            "Hubei",
            "Hunan",
            "Inner Mongolia",
            "Jiangsu",
            "Jiangxi",
            "Jilin",
            "Liaoning",
            "Macau",
            "Ningxia",
            "Qinghai",
            "Shaanxi",
            "Shandong",
            "Shanghai",
            "Shanxi",
            "Sichuan",
            "Tianjin",
            "Tibet",
            "Xinjiang",
            "Yunnan",
            "Zhejiang",
            "Antioquia",
            "Arauca",
            "Atlantico",
            "Bolivar",
            "Boyaca",
            "Caldas",
            "Capital District",
            "Caqueta",
            "Casanare",
            "Cauca",
            "Cesar",
            "Choco",
            "Cordoba",
            "Cundinamarca",
            "Guainia",
            "Guaviare",
            "Huila",
            "La Guajira",
            "Magdalena",
            "Meta",
            "Narino",
            "Norte de Santander",
            "Putumayo",
            "Quindio",
            "Risaralda",
            "San Andres y Providencia",
            "Santander",
            "Sucre",
            "Tolima",
            "Valle del Cauca",
            "Vaupes",
            "Vichada",
            "Faroe Islands",
            "Greenland",
            "French Guiana",
            "French Polynesia",
            "Guadeloupe",
            "Martinique",
            "Mayotte",
            "New Caledonia",
            "Reunion",
            "Saint Barthelemy",
            "Saint Pierre and Miquelon",
            "St Martin",
            "Wallis and Futuna",
            "Baden-Wurttemberg",
            "Bayern",
            "Berlin",
            "Brandenburg",
            "Bremen",
            "Hamburg",
            "Hessen",
            "Mecklenburg-Vorpommern",
            "Niedersachsen",
            "Nordrhein-Westfalen",
            "Rheinland-Pfalz",
            "Saarland",
            "Sachsen",
            "Sachsen-Anhalt",
            "Schleswig-Holstein",
            "Thuringen",
            "Andaman and Nicobar Islands",
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chandigarh",
            "Chhattisgarh",
            "Dadra and Nagar Haveli and Daman and Diu",
            "Delhi",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jammu and Kashmir",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Ladakh",
            "Lakshadweep",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Puducherry",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttar Pradesh",
            "Uttarakhand",
            "West Bengal",
            "Abruzzo",
            "Basilicata",
            "Calabria",
            "Campania",
            "Emilia-Romagna",
            "Friuli Venezia Giulia",
            "Lazio",
            "Liguria",
            "Lombardia",
            "Marche",
            "Molise",
            "P.A. Bolzano",
            "P.A. Trento",
            "Piemonte",
            "Puglia",
            "Sardegna",
            "Sicilia",
            "Toscana",
            "Umbria",
            "Valle d'Aosta",
            "Veneto",
            "Aichi",
            "Akita",
            "Aomori",
            "Chiba",
            "Ehime",
            "Fukui",
            "Fukuoka",
            "Fukushima",
            "Gifu",
            "Gunma",
            "Hiroshima",
            "Hokkaido",
            "Hyogo",
            "Ibaraki",
            "Ishikawa",
            "Iwate",
            "Kagawa",
            "Kagoshima",
            "Kanagawa",
            "Kochi",
            "Kumamoto",
            "Kyoto",
            "Mie",
            "Miyagi",
            "Miyazaki",
            "Nagano",
            "Nagasaki",
            "Nara",
            "Niigata",
            "Oita",
            "Okayama",
            "Okinawa",
            "Osaka",
            "Port Quarantine",
            "Saga",
            "Saitama",
            "Shiga",
            "Shimane",
            "Shizuoka",
            "Tochigi",
            "Tokushima",
            "Tokyo",
            "Tottori",
            "Toyama",
            "Wakayama",
            "Yamagata",
            "Yamaguchi",
            "Yamanashi",
            "Aguascalientes",
            "Baja California",
            "Baja California Sur",
            "Campeche",
            "Chiapas",
            "Chihuahua",
            "Ciudad de Mexico",
            "Coahuila",
            "Colima",
            "Durango",
            "Guanajuato",
            "Guerrero",
            "Hidalgo",
            "Jalisco",
            "Michoacan",
            "Morelos",
            "Nayarit",
            "Nuevo Leon",
            "Oaxaca",
            "Puebla",
            "Queretaro",
            "Quintana Roo",
            "San Luis Potosi",
            "Sinaloa",
            "Sonora",
            "Tabasco",
            "Tamaulipas",
            "Tlaxcala",
            "Veracruz",
            "Yucatan",
            "Zacatecas",
            "Aruba",
            "Bonaire",
            "Sint Eustatius and Saba",
            "Curacao",
            "Drenthe",
            "Flevoland",
            "Friesland",
            "Gelderland",
            "Groningen",
            "Noord-Brabant",
            "Noord-Holland",
            "Overijssel",
            "Sint Maarten",
            "Utrecht",
            "Zeeland",
            "Zuid-Holland",
            "Azad Jammu and Kashmir",
            "Balochistan",
            "Gilgit-Baltistan",
            "Islamabad",
            "Khyber Pakhtunkhwa",
            "Sindh",
            "Ancash",
            "Apurimac",
            "Arequipa",
            "Ayacucho",
            "Cajamarca",
            "Callao",
            "Cusco",
            "Huancavelica",
            "Huanuco",
            "Ica",
            "Junin",
            "La Libertad",
            "Lambayeque",
            "Lima",
            "Loreto",
            "Madre de Dios",
            "Moquegua",
            "Pasco",
            "Piura",
            "Puno",
            "San Martin",
            "Tacna",
            "Tumbes",
            "Ucayali",
            "Adygea Republic",
            "Altai Krai",
            "Altai Republic",
            "Amur Oblast",
            "Arkhangelsk Oblast",
            "Astrakhan Oblast",
            "Bashkortostan Republic",
            "Belgorod Oblast",
            "Bryansk Oblast",
            "Buryatia Republic",
            "Chechen Republic",
            "Chelyabinsk Oblast",
            "Chukotka Autonomous Okrug",
            "Chuvashia Republic",
            "Dagestan Republic",
            "Ingushetia Republic",
            "Irkutsk Oblast",
            "Ivanovo Oblast",
            "Jewish Autonomous Okrug",
            "Kabardino-Balkarian Republic",
            "Kaliningrad Oblast",
            "Kalmykia Republic",
            "Kaluga Oblast",
            "Kamchatka Krai",
            "Karachay-Cherkess Republic",
            "Karelia Republic",
            "Kemerovo Oblast",
            "Khabarovsk Krai",
            "Khakassia Republic",
            "Khanty-Mansi Autonomous Okrug",
            "Kirov Oblast",
            "Komi Republic",
            "Kostroma Oblast",
            "Krasnodar Krai",
            "Krasnoyarsk Krai",
            "Kurgan Oblast",
            "Kursk Oblast",
            "Leningrad Oblast",
            "Lipetsk Oblast",
            "Magadan Oblast",
            "Mari El Republic",
            "Mordovia Republic",
            "Moscow",
            "Moscow Oblast",
            "Murmansk Oblast",
            "Nenets Autonomous Okrug",
            "Nizhny Novgorod Oblast",
            "North Ossetia - Alania Republic",
            "Novgorod Oblast",
            "Novosibirsk Oblast",
            "Omsk Oblast",
            "Orel Oblast",
            "Orenburg Oblast",
            "Penza Oblast",
            "Perm Krai",
            "Primorsky Krai",
            "Pskov Oblast",
            "Rostov Oblast",
            "Ryazan Oblast",
            "Saint Petersburg",
            "Sakha (Yakutiya) Republic",
            "Sakhalin Oblast",
            "Samara Oblast",
            "Saratov Oblast",
            "Smolensk Oblast",
            "Stavropol Krai",
            "Sverdlovsk Oblast",
            "Tambov Oblast",
            "Tatarstan Republic",
            "Tomsk Oblast",
            "Tula Oblast",
            "Tver Oblast",
            "Tyumen Oblast",
            "Tyva Republic",
            "Udmurt Republic",
            "Ulyanovsk Oblast",
            "Vladimir Oblast",
            "Volgograd Oblast",
            "Vologda Oblast",
            "Voronezh Oblast",
            "Yamalo-Nenets Autonomous Okrug",
            "Yaroslavl Oblast",
            "Zabaykalsky Krai",
            "Andalusia",
            "Aragon",
            "Asturias",
            "Baleares",
            "C. Valenciana",
            "Canarias",
            "Cantabria",
            "Castilla - La Mancha",
            "Castilla y Leon",
            "Catalonia",
            "Ceuta",
            "Extremadura",
            "Galicia",
            "La Rioja",
            "Madrid",
            "Melilla",
            "Murcia",
            "Navarra",
            "Pais Vasco",
            "Blekinge",
            "Dalarna",
            "Gavleborg",
            "Gotland",
            "Halland",
            "Jamtland Harjedalen",
            "Jonkoping",
            "Kalmar",
            "Kronoberg",
            "Norrbotten",
            "Orebro",
            "Ostergotland",
            "Skane",
            "Sormland",
            "Stockholm",
            "Uppsala",
            "Varmland",
            "Vasterbotten",
            "Vasternorrland",
            "Vastmanland",
            "Vastra Gotaland",
            "Guam",
            "Northern Mariana Islands",
            "Recovered",
            "Virgin Islands",
            "Cherkasy Oblast",
            "Chernihiv Oblast",
            "Chernivtsi Oblast",
            "Crimea Republic*",
            "Dnipropetrovsk Oblast",
            "Donetsk Oblast",
            "Ivano-Frankivsk Oblast",
            "Kharkiv Oblast",
            "Kherson Oblast",
            "Khmelnytskyi Oblast",
            "Kiev",
            "Kiev Oblast",
            "Kirovohrad Oblast",
            "Luhansk Oblast",
            "Lviv Oblast",
            "Mykolaiv Oblast",
            "Odessa Oblast",
            "Poltava Oblast",
            "Rivne Oblast",
            "Sevastopol*",
            "Sumy Oblast",
            "Ternopil Oblast",
            "Vinnytsia Oblast",
            "Volyn Oblast",
            "Zakarpattia Oblast",
            "Zaporizhia Oblast",
            "Zhytomyr Oblast",
            "Anguilla",
            "Bermuda",
            "British Virgin Islands",
            "Cayman Islands",
            "Channel Islands",
            "England",
            "Falkland Islands (Malvinas)",
            "Gibraltar",
            "Isle of Man",
            "Montserrat",
            "Northern Ireland",
            "Saint Helena",
            "Ascension and Tristan da Cunha",
            "Scotland",
            "Turks and Caicos Islands",
            "Wales",
            "Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "District of Columbia",
            "Florida",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Puerto Rico",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming"
        )
    }
}